### ISSUE TITLE
The compatible issue between MMM-CalendarExt2, MMM-GroveGestures and MMM-pages

### ISSUE THREAD

**Issue by xuepgao** [eouia/MMM-CalendarExt2#20]
Hi @eouia 

I'm trying out this module MMM-CalendarExt2. I'm also using  other modules, MMM-GroveGestures,MMM-pages, etc.

I found that there is a compatible issue between MMM-CalendarExt2, MMM-GroveGestures and MMM-pages. 

While switching pages by mouse or touch control, the page loads fine :
[https://drive.google.com/open?id=1tJ70z-4w1dCM5nzw3CTUBcVPhO55P786](https://drive.google.com/open?id=1tJ70z-4w1dCM5nzw3CTUBcVPhO55P786)

However, while switching pages by gesture control, the page loads abnormally:
[https://drive.google.com/open?id=1JXSZvgP9G5bdLB9gy-tmY8hN5317ViYE](https://drive.google.com/open?id=1JXSZvgP9G5bdLB9gy-tmY8hN5317ViYE)

Could you give me some suggestion? Thanks in advance.

**Comment by eouia** [comment]
Show your configuration of MMM-GroveGestures

**Comment by xuepgao** [comment]
Hi @eouia 

My configuration is as following:
```
		{
			module: "MMM-GroveGestures",
			position: "bottom_left",
			config: {
				autoStart: true, 
				verbose: true, 
				recognitionTimeout: 700, 
				cancelGesture: "WAVE", 
				visible: true,	  
				idleTimer: 0, 
				onIdle: { 
					moduleExec: {
						module: [],
						exec: (module, gestures) => {
							module.hide(1000, null, {lockstring:"GESTURE"});
						}
					}
				},
				onDetected: {
					notificationExec: {
						notification: "GESTURE_DETECTED",
					},
					moduleExec: {
						module: [],
						exec: (module) => {
							module.show(1000, null, {lockstring:"GESTURE"});
						}
					}
				},

				gestureMapFromTo: { 
					"Up": "RIGHT",
					"Down": "LEFT",
					"Left": "UP",
					"Right": "DOWN",
					"Forward": "FORWARD",
					"Backward": "BACKWARD",
					"Clockwise": "CLOCKWISE",
					"anti-clockwise": "ANTICLOCKWISE",
					"wave": "WAVE"
				},

				defaultNotification: "GESTURE",
				pythonPath: "/usr/bin/python3", // your python path

				defaultCommandSet: "default",
				commandSet: {
					"default": {
						"FORWARD-BACKWARD": {
							notificationExec: {
								notification: "ASSISTANT_ACTIVATE",
								payload: null
							}
						},
						"LEFT-RIGHT": {
							notificationExec: {
								notification: "ASSISTANT_CLEAR",
								payload:null,
							}
						},
						"ANTICLOCKWISE": {
							moduleExec: {
								module: [],
								exec: (module, gestures) => {
									module.hide(1000, null, {lockstring:"GESTURE"});
								}
							}
						},
						"CLOCKWISE": {
							moduleExec: {
								module: [],
								exec: (module, gestures) => {
									module.show(1000, null, {lockstring:"GESTURE"});
								}
							}
						},
						"LEFT": {
							notificationExec: {
								notification: "PAGE_INCREMENT",
								payload: null,
							}
						},
						"RIGHT": {
							notificationExec: {
								notification: "PAGE_DECREMENT",
								payload: null,
							}
						},
						"UP": {
							notificationExec: {
								notification: "VOLUME_UP",
								payload: null,
							}
						},
						"DOWN": {
							notificationExec: {
								notification: "VOLUME_DOWN",
								payload: null,
							}
						},

					},
				},
				commandSetTrigger: {
					"GG_CHANGE_COMMANDSET_NEWSMODE": "NEWS_MODE",
					"GG_CHANGE_COMMANDSET_BY_PAYLOAD": (payload) => { 
						return payload.commandSetName;
					}
				},
			}
......
		{
			module: 'MMM-pages',
			name: "MMM-pages",
			classes: 'default',
			position: "bottom_bar",
			config: {
				animationTime: 0,
				modules:
					[
						["clock", "MMM-newsfeedtouch"],
						["MMM-Timetable"],
						["MMM-CalendarExt2"],
						["calendar","calendar_monthly"], 
						["currentweather", "MMM-ping", "MMM-SystemStats"],
						["MMM-SmartWebDisplay"],
					],
				fixed: 
				["MMM-GroveGestures", "MMM-page-indicator","MMM-Volume"]
			}
		},
```

**Comment by eouia** [comment]
Nothing seems wrong in your Gesture configuration. With my test (emittance PAGE_INCREMENT by force) has no problem. The lazy loading issue of MMM-CalendarExt2 was solved(in my thought) already. When did you update or install MMM-CalendarExt2 lastly?

If your issue is not due to old version, I think real-time examining for your mirror might be needed. Do you have Telegarm? my telegram id is "@eouia". I'm convenient on any weekday except Friday. You can contact me with Telegram by German local time (10:00 ~20:00)

**Comment by xuepgao** [comment]
Hi @eouia
Thank you for your prompt reply.

I install directly MMM-CalendarExt2 new version yesterday. I haven't installed old version before.
Troubleshooting will spend your personal time, especially by remote access. I am really touched by you. You are so kind!

Honestly speaking, I'm not unfamiliar with Telegram. Let me try it out in advance. I am also OK with Webex or Teamviewer. I emphasize again, the issue is not urgent. It's up to your time for troubleshooting remotely.

Let's keep touch with each other with Telegram.
Thanks again!

**Comment by Pengree** [comment]
Hi @eouia,
I ping you at Telegram. I'm not sure you received my messages. It seems like that your Telegram is DND (Do Not Disturb).

To simplify the complexity of the issue, I remove/reinstall MMM-CalendarExt2 and delete other modules in config.js. Now there are 4 modules config (MMM-logging, MMM-GroveGestures,MMM-pages, MMM-page-indicator) in config.js, the problem still exists. I'm almost sure there is a compatible issue.
[https://drive.google.com/open?id=1jOWfoSB_WNupsOw7yVRpm4z_f8uXwWHM](https://drive.google.com/open?id=1jOWfoSB_WNupsOw7yVRpm4z_f8uXwWHM)

You can ping me @xuepgao with Telegram. And you can tell me when you are available.

**Comment by xuepgao** [comment]
Hi @eouia,
I ping you at Telegram. I'm not sure you received my messages. It seems like that your Telegram is DND (Do Not Disturb).

To simplify the complexity of the issue, I remove/reinstall MMM-CalendarExt2 and delete other modules in config.js. Now there are 4 modules config (MMM-logging, MMM-GroveGestures,MMM-pages, MMM-page-indicator) in config.js, the problem still exists. I'm almost sure there is a compatible issue.
[https://drive.google.com/open?id=1jOWfoSB_WNupsOw7yVRpm4z_f8uXwWHM](https://drive.google.com/open?id=1jOWfoSB_WNupsOw7yVRpm4z_f8uXwWHM)

You can ping me @xuepgao with Telegram. And you can tell me when you are available.

**Comment by xuepgao** [comment]
Thanks @eouia so much! 
He help me to resolved this issue. The root cause is that I turn on the **onDetected** feature (it is turn off by default):
![image](https://user-images.githubusercontent.com/48181152/56181550-91b14c80-6040-11e9-8712-ca16b7e09dac.png)

Please keep the default **onDetected** Settings. If you turn it on, please comment it out:
```
    onDetected: {
      notificationExec: {
        notification: "GESTURE_DETECTED",
      },
      /* You can make Mirror to wake up the modules which were hidden by onIdle with any gestures.
      moduleExec: {
        module: [],
        exec: (module) => {
          module.show(1000, null, {lockstring:"GESTURE"})
        }
      }
      */
    },
```

Thanks eouia again!
